### ISSUE TITLE
helm init returns 403 due to deprecated kubernetes charts url

### ISSUE THREAD

**Issue by xtremerui** [linkyard/helm-chart-resource#8]
When resource checking it returns

```
Initializing helm...
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

this should be used instead
```
helm init --stable-repo-url=https://charts.helm.sh/stable --client-only 
```

**Comment by arbourd** [comment]
Strange. Does Helm 3 auto init with the deprecated endpoint still?

**Comment by arbourd** [comment]
Oh right, Helm 3 doesn't have `init`. So I think this needs to be updated to support both versions of Helm or abandon 2 entirely.

**Comment by will-gant** [comment]
Thanks for the fix - would it be possible to push a new build to Dockerhub as well please?

**Comment by arbourd** [comment]
@msiegenthaler

**Comment by msiegenthaler** [comment]
I've pushed linkyard/helm-chart-resource:2.17.0 now

was: Doesn't linkyard/concourse-helm-resource:2.17.0 work? > sorry, wrong repo :)

**Comment by will-gant** [comment]
Thanks!
